[libraries]
cardano-client-core = "com.bloxbean.cardano:cardano-client-core:0.5.0-beta1"
cbor = "co.nstant.in:cbor:0.9"
netty = "io.netty:netty-all:4.1.92.Final"
project-reactor-core = "io.projectreactor:reactor-core:3.5.5"
project-reactor-test = "io.projectreactor:reactor-test:3.5.5"

slf4j-api = "org.slf4j:slf4j-api:1.7.36"
slf4j-log4j="org.slf4j:slf4j-log4j12:1.7.36"

lombok="org.projectlombok:lombok:1.18.20"

junit-jupiter-api="org.junit.jupiter:junit-jupiter-api:5.8.1"
junit-jupiter-engine="org.junit.jupiter:junit-jupiter-engine:5.8.1"
harmcrest-library="org.hamcrest:hamcrest-library:2.2"

mockito-inline="org.mockito:mockito-inline:3.7.7"
mockito-junit-jupiter="org.mockito:mockito-junit-jupiter:3.7.7"
assertj-core="org.assertj:assertj-core:3.21.0"

