package com.bloxbean.cardano.yaci.core.model.certs;

public enum CertificateType {
    STAKE_REGISTRATION,
    STAKE_DEREGISTRATION,
    STAKE_DELEGATION,
    POOL_REGISTRATION,
    POOL_RETIREMENT,
    GENESIS_KEY_DELEGATION,
    MOVE_INSTATENEOUS_REWARDS_CERT,

    //conway
    //Delegation certs
    REG_CERT,
    UNREG_CERT,
    VOTE_DELEG_CERT,
    STAKE_VOTE_DELEG_CERT,
    STAKE_REG_DELEG_CERT,
    VOTE_REG_DELEG_CERT,
    STAKE_VOTE_REG_DELEG_CERT,

    //Gov certs
    AUTH_COMMITTEE_HOT_CERT,
    RESIGN_COMMITTEE_COLD_CERT,
    REG_DREP_CERT,
    UNREG_DREP_CERT,
    UPDATE_DREP_CERT
}
