quarkus:
  application:
    name: yaci-node
  package:
    output-name: yaci-node
    jar:
      add-runner-suffix: false
  http:
    port: 8080
    test-port: 0
  log:
    level: INFO
    category:
      "com.bloxbean.cardano.yaci":
        level: INFO
  smallrye-openapi:
    info-title: "Yaci Node API"
    info-version: "${quarkus.application.version:0.1.0}"
    info-description: "Cardano Yaci Node REST API"
  swagger-ui:
    always-include: ${YACI_SWAGGER_UI_ENABLED:true}
    path: /q/swagger-ui
  banner:
    enabled: true
    path: "banner.txt"

yaci:
  events:
    enabled: true
  plugins:
    enabled: true
    directory: plugins
    logging:
      enabled: false
  node:
    network: preprod
    auto-sync-start: true
    client:
      enabled: true
    remote:
      host: preprod-node.world.dev.cardano.org
      port: 30000
      protocol-magic: 1
    server:
      enabled: true
      port: 13337
    storage:
      rocksdb: true
      path: "./chainstate"
    genesis:
      shelley-genesis-file:
      byron-genesis-file:
      protocol-parameters-file:
    block-producer:
      enabled: false
      block-time-millis: 0
      lazy: false
      genesis-timestamp: 0
      slot-length-millis: 0
      tx-evaluation: true

"%native":
  quarkus:
    package:
      jar:
        enabled: false
    native:
      enabled: true

"%devnet":
  yaci:
    node:
      network: devnet
      auto-sync-start: true
      client:
        enabled: false
      remote:
        protocol-magic: 42
      genesis:
        shelley-genesis-file: config/devnet/shelley-genesis.json
        protocol-parameters-file: config/protocol-param.json
      block-producer:
        enabled: true
        block-time-millis: 0
        lazy: false
        genesis-timestamp: 0
        slot-length-millis: 0

"%test":
  yaci:
    events:
      enabled: true
    plugins:
      enabled: false
      logging:
        enabled: false
    node:
      auto-sync-start: false
      client:
        enabled: false
      server:
        enabled: true
      storage:
        rocksdb: false
        path: "./chainstate-test"
